version: "3.8"
services:
  app :
    build: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - app.env
  db:
    image: postgres:14.1
    env_file:
      - db.env
    ports:
      - "5432:5432"