version: "3.8"
services:
  app :
    build: .
    hostname: devsocialapp
    ports:
      - "8080:8080"
    env_file:
      - app.env
    depends_on:
      - db
  db:
    image: postgres:14.1
    hostname: devsocialdb
    ports:
      - "5432:5432"
    env_file:
      - db.env