name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - uses: checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Generate Report
      run: |
        pip install -r requirements_dev.txt
        coverage run -m pytest tests
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./htmlcov/index.html
        verbose: true